[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
which = "5.0"
cargo_metadata = "0.15"
