[package]
name = "rustagon-e2e-evtgen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = "1"
rustagon-engine = { path = "../../../rustagon-engine" }
rustagon-scap = { path = "../../../rustagon-scap" }
rustagon-sinsp = { path = "../../../rustagon-sinsp" }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
