use super::{fields, FieldInfo};

pub(super) const FIELDS: &[FieldInfo] = fields!(Evt;
    ("evt.abspath", "Absolute Path"),
    ("evt.arg", "Argument"),
    ("evt.args", "Arguments"),
    ("evt.around", "Around Interval"),
    ("evt.asynctype", "Async-Event Type"),
    ("evt.buffer", "Buffer"),
    ("evt.buflen", "Buffer Length"),
    ("evt.buflen.file", "File Buffer Length"),
    ("evt.buflen.file.in", "File Input Buffer Length"),
    ("evt.buflen.file.out", "File Output Buffer Length"),
    ("evt.buflen.in", "Input Buffer Length"),
    ("evt.buflen.net", "Network Buffer Length"),
    ("evt.buflen.net.in", "Network Input Buffer Length"),
    ("evt.buflen.net.out", "Network Output Buffer Length"),
    ("evt.buflen.out", "Output Buffer Length"),
    ("evt.category", "Category"),
    ("evt.count", "Count"),
    ("evt.count.error", "Error Count"),
    ("evt.count.error.file", "File Error Count"),
    ("evt.count.error.memory", "Memory Error Count"),
    ("evt.count.error.net", "Network Error Count"),
    ("evt.count.error.other", "Other Error Count"),
    ("evt.count.exit", "Exit Count"),
    ("evt.count.procinfo", "Procinfo Count"),
    ("evt.count.threadinfo", "Thread Info Count"),
    ("evt.cpu", "CPU Number"),
    ("evt.datetime", "Datetime"),
    ("evt.datetime.s", "Datetime (s)"),
    ("evt.deltatime", "Delta"),
    ("evt.deltatime.ns", "Delta (ns)"),
    ("evt.deltatime.s", "Delta (s)"),
    ("evt.dir", "Direction"),
    ("evt.failed", "Failed"),
    ("evt.hostname", "Hostname"),
    ("evt.info", "Information"),
    ("evt.infra.docker.container.id", "Docker ID"),
    ("evt.infra.docker.container.image", "Container Image"),
    ("evt.infra.docker.container.name", "Container Name"),
    ("evt.infra.docker.name", "Docker Name"),
    ("evt.io_dir", "I/O Direction"),
    ("evt.is_async", "Async Event"),
    ("evt.is_io", "Is I/O"),
    ("evt.is_io_read", "Is Read"),
    ("evt.is_io_write", "Is Write"),
    ("evt.is_open_create", "Is Created"),
    ("evt.is_open_exec", "Is Created With Execute Permissions"),
    ("evt.is_open_read", "Is Opened For Reading"),
    ("evt.is_open_write", "Is Opened For Writing"),
    ("evt.is_syslog", "Is Syslog"),
    ("evt.is_wait", "Is Wait"),
    ("evt.latency", "Latency"),
    ("evt.latency.human", "Human-Readable Latency"),
    ("evt.latency.ns", "Latency (ns)"),
    ("evt.latency.quantized", "Quantized Latency"),
    ("evt.latency.s", "Latency (s)"),
    ("evt.num", "Event Number"),
    ("evt.outputtime", "Output Time"),
    ("evt.plugininfo", "Plugin Info"),
    ("evt.pluginname", "Plugin Name"),
    ("evt.rawarg", "Raw Argument"),
    ("evt.rawres", "Raw Return Value"),
    ("evt.rawtime", "Absolute Time"),
    ("evt.rawtime.ns", "Absolute Time (ns)"),
    ("evt.rawtime.s", "Absolute Time (s)"),
    ("evt.reltime", "Relative Time"),
    ("evt.reltime.ns", "Relative Time (ns)"),
    ("evt.reltime.s", "Relative Time (s)"),
    ("evt.res", "Return Value"),
    ("evt.source", "Event Source"),
    ("evt.time", "Time"),
    ("evt.time.iso8601", "ISO 8601 Time"),
    ("evt.time.s", "Time (s)"),
    ("evt.type", "Type"),
    ("evt.type.is", "Type Is"),
    ("evt.wait_latency", "Wait Latency"),
);
