use super::{fields, FieldInfo};

pub(super) const FIELDS: &[FieldInfo] = fields!(Fd;
    ("fd.cip", "FD Client Address"),
    ("fd.cip.name", "FD Client Domain Name"),
    ("fd.cnet", "FD Client Network"),
    ("fd.connected", "FD Connected"),
    ("fd.containerdirectory", "FD Container Directory"),
    ("fd.containername", "FD Container Name"),
    ("fd.cport", "FD Client Port"),
    ("fd.cproto", "FD Client Protocol"),
    ("fd.dev", "FD Device"),
    ("fd.dev.major", "FD Major Device"),
    ("fd.dev.minor", "FD Minor Device"),
    ("fd.directory", "FD Directory"),
    ("fd.filename", "FD Filename"),
    ("fd.ino", "FD Inode Number"),
    ("fd.ip", "FD IP Address"),
    ("fd.is_lower_layer", "FD Lower Layer"),
    ("fd.is_server", "FD Server"),
    ("fd.is_upper_layer", "FD Upper Layer"),
    ("fd.l4proto", "FD IP Protocol"),
    ("fd.lip", "FD Local Address"),
    ("fd.lip.name", "FD Local Domain Name"),
    ("fd.lnet", "FD Local Network"),
    ("fd.lport", "FD Local Port"),
    ("fd.lproto", "FD Local Protocol"),
    ("fd.name", "FD Name"),
    ("fd.name_changed", "FD Name Changed"),
    ("fd.nameraw", "FD Name Raw"),
    ("fd.net", "FD IP Network"),
    ("fd.num", "FD Number"),
    ("fd.port", "FD Port"),
    ("fd.proto", "FD Protocol"),
    ("fd.rip", "FD Remote Address"),
    ("fd.rip.name", "FD Remote Domain Name"),
    ("fd.rnet", "FD Remote Network"),
    ("fd.rport", "FD Remote Port"),
    ("fd.rproto", "FD Remote Protocol"),
    ("fd.sip", "FD Server Address"),
    ("fd.sip.name", "FD Server Domain Name"),
    ("fd.snet", "FD Server Network"),
    ("fd.sockfamily", "FD Socket Family"),
    ("fd.sport", "FD Server Port"),
    ("fd.sproto", "FD Server Protocol"),
    ("fd.type", "FD Type"),
    ("fd.typechar", "FD Type Char"),
    ("fd.types", "FD Types"),
    ("fd.uid", "FD ID"),
);
