use super::{fields, FieldInfo};

pub(super) const FIELDS: &[FieldInfo] = fields!(Proc;
    ("proc.acmdline", "Ancestor Command Line"),
    ("proc.aenv", "Ancestor Environment"),
    ("proc.aexe", "Ancestor First Argument"),
    ("proc.aexepath", "Ancestor Executable Path"),
    ("proc.aargs", "Ancestor Arguments"),
    ("proc.aname", "Ancestor Name"),
    ("proc.apid", "Ancestor Process ID"),
    ("proc.args", "Arguments"),
    ("proc.cmdlenargs", "Command Line Argument Length"),
    ("proc.cmdline", "Command Line"),
    ("proc.cmdnargs", "Number of Command Line Arguments"),
    ("proc.cwd", "Current Working Directory"),
    ("proc.duration", "Process Duration"),
    ("proc.env", "Environment"),
    ("proc.exe", "First Argument"),
    ("proc.exe_ino", "Executable Inode"),
    ("proc.exe_ino.ctime", "Executable Inode Change Time"),
    (
        "proc.exe_ino.ctime_duration_pidns_start",
        "Executable Change Time Since PID Namespace Start"
    ),
    (
        "proc.exe_ino.ctime_duration_proc_start",
        "Executable Change Time Since Process Start"
    ),
    ("proc.exe_ino.mtime", "Executable Inode Modification Time"),
    ("proc.exeline", "Executable Command Line"),
    ("proc.exepath", "Process Executable Path"),
    ("proc.fdlimit", "FD Limit"),
    ("proc.fdopencount", "FD Count"),
    ("proc.fdusage", "FD Usage"),
    ("proc.is_exe_from_memfd", "Process Executable Is Stored In Memfd"),
    ("proc.is_exe_lower_layer", "Process Executable Is In Lower Layer"),
    ("proc.is_exe_upper_layer", "Process Executable Is In Upper Layer"),
    ("proc.is_exe_writable", "Process Executable Is Writable"),
    ("proc.is_pgid_leader", "Process Is Process Group Leader"),
    ("proc.is_sid_leader", "Process Is Session Leader"),
    ("proc.is_vpgid_leader", "Process Is Virtual Process Group Leader"),
    ("proc.loginshellid", "Login Shell ID"),
    ("proc.name", "Name"),
    ("proc.nchilds", "Children"),
    ("proc.nthreads", "Threads"),
    ("proc.pcmdline", "Parent Command Line"),
    ("proc.pexe", "Parent First Argument"),
    ("proc.pexepath", "Parent Process Executable Path"),
    ("proc.pgid", "Process Group ID"),
    ("proc.pgid.exe", "Process Group First Argument"),
    ("proc.pgid.exepath", "Process Group Executable Path"),
    ("proc.pgid.name", "Process Group Name"),
    ("proc.pid", "Process ID"),
    ("proc.pid.ts", "Process Start Timestamp"),
    ("proc.pidns_init_start_ts", "PID Namespace Start Timestamp"),
    ("proc.pname", "Parent Name"),
    ("proc.ppid", "Parent Process ID"),
    ("proc.ppid.duration", "Parent Process Duration"),
    ("proc.ppid.ts", "Parent Process Start Timestamp"),
    ("proc.pvpid", "Parent Virtual Process ID"),
    ("proc.sid", "Process Session ID"),
    ("proc.sid.exe", "Process Session First Argument"),
    ("proc.sid.exepath", "Process Session Executable Path"),
    ("proc.sname", "Process Session Name"),
    ("proc.stderr.name", "Standard Error FD Name"),
    ("proc.stderr.type", "Standard Error FD Type"),
    ("proc.stdin.name", "Standard Input FD Name"),
    ("proc.stdin.type", "Standard Input FD Type"),
    ("proc.stdout.name", "Standard Output FD Name"),
    ("proc.stdout.type", "Standard Output FD Type"),
    ("proc.tty", "Process TTY"),
    ("proc.vmrss", "VM RSS"),
    ("proc.vmsize", "VM Size"),
    ("proc.vmswap", "VM Swap"),
    ("proc.vpgid", "Process Virtual Group ID"),
    ("proc.vpgid.exe", "Virtual Process Group First Argument"),
    ("proc.vpgid.exepath", "Virtual Process Group Executable Path"),
    ("proc.vpgid.name", "Virtual Process Group Name"),
    ("proc.vpid", "Virtual Process ID"),
);
