#!/usr/bin/env python3
"""Generate Rust lookup tables from falcosecurity/libs.

The generated file is checked in so building Rustagon never requires a Falco
source checkout. Regenerate it from the matching libs tag with:

  python3 rustagon-app/scripts/generate_ppm_events.py \
      --libs-root /tmp/falco-libs \
      --output rustagon-app/src/ppm_events.rs
"""

import argparse
import collections
import pathlib
import re


def rust_slice(name: str, values: set[str] | list[str]) -> str:
    body = "\n".join(f'    "{value}",' for value in sorted(values))
    return f"pub(crate) const {name}: &[&str] = &[\n{body}\n];\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--libs-root", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()

    public_h = (args.libs_root / "driver/ppm_events_public.h").read_text()
    event_table = (args.libs_root / "driver/event_table.c").read_text()
    event_map = (
        args.libs_root / "userspace/libscap/linux/scap_ppm_sc.c"
    ).read_text()
    ppm_tests = (
        args.libs_root
        / "userspace/libsinsp/test/public_sinsp_API/ppm_sc_codes.cpp"
    ).read_text()

    public_h_without_comments = re.sub(r"/\*.*?\*/", "", public_h, flags=re.S)
    codes = {
        symbol: (int(value), symbol.lower())
        for symbol, value in re.findall(
            r"PPM_SC_X\(\s*([A-Z0-9_]+)\s*,\s*(\d+)\s*\)",
            public_h_without_comments,
        )
    }

    event_to_symbols: dict[str, set[str]] = {}
    for event, body in re.findall(
        r"\[(PPME_[A-Z0-9_]+)\]\s*=\s*\(ppm_sc_code\[\]\)\s*\{(.*?)\}",
        event_map,
        re.S,
    ):
        event_to_symbols[event] = set(re.findall(r"PPM_SC_([A-Z0-9_]+)", body))

    event_info: dict[str, tuple[str, str]] = {}
    for event, name, category in re.findall(
        r'\[(PPME_[A-Z0-9_]+)\]\s*=\s*\{\s*"([^"]+)"\s*,\s*([^,]+),',
        event_table,
        re.S,
    ):
        event_info[event] = (name, category.strip())

    mappings: dict[str, set[str]] = collections.defaultdict(set)
    categories: dict[str, set[str]] = collections.defaultdict(set)
    kernel_event_names: set[str] = set()
    for event, (name, category) in event_info.items():
        if name not in {"NA", "syscall"}:
            kernel_event_names.add(name)
        syscall_names = {
            codes[symbol][1]
            for symbol in event_to_symbols.get(event, set())
            if symbol in codes and symbol != "UNKNOWN"
        }
        if syscall_names and name not in {"NA", "syscall"}:
            mappings[name].update(syscall_names)
        for category_name in (
            "EC_NET",
            "EC_FILE",
            "EC_IO_READ",
            "EC_IO_WRITE",
            "EC_IO_OTHER",
        ):
            if category.split("|", 1)[0].strip() == category_name:
                categories[category_name].update(syscall_names)

    generic_symbols = event_to_symbols["PPME_GENERIC_E"] | event_to_symbols[
        "PPME_GENERIC_X"
    ]
    generic_names = {
        codes[symbol][1]
        for symbol in generic_symbols
        if symbol in codes and symbol != "UNKNOWN"
    }

    default_match = re.search(
        r"expected_sinsp_state_sc_set\s*=\s*\{(.*?)\};", ppm_tests, re.S
    )
    if default_match is None:
        raise RuntimeError("expected_sinsp_state_sc_set not found")
    default_names = {
        codes[symbol][1]
        for symbol in re.findall(r"PPM_SC_([A-Z0-9_]+)", default_match.group(1))
    }

    all_names = {
        name for symbol, (_, name) in codes.items() if symbol != "UNKNOWN"
    }
    mapping_lines = []
    for name, syscall_names in sorted(mappings.items()):
        values = ", ".join(f'"{value}"' for value in sorted(syscall_names))
        mapping_lines.append(f'    ("{name}", &[{values}]),')

    generated = f"""// @generated by scripts/generate_ppm_events.py from falcosecurity/libs 0.26.0-rc1.
// Do not edit by hand.

{rust_slice("ALL_SYSCALL_NAMES", all_names)}
{rust_slice("GENERIC_SYSCALL_NAMES", generic_names)}
{rust_slice("DEFAULT_STATE_SYSCALL_NAMES", default_names)}
{rust_slice("NETWORK_SYSCALL_NAMES", categories["EC_NET"])}
{rust_slice("IO_SYSCALL_NAMES", categories["EC_IO_READ"] | categories["EC_IO_WRITE"])}
{rust_slice("FD_RELATED_SYSCALL_NAMES", categories["EC_FILE"] | categories["EC_IO_READ"] | categories["EC_IO_WRITE"] | categories["EC_IO_OTHER"])}
{rust_slice("KERNEL_EVENT_NAMES", kernel_event_names)}
pub(crate) const EVENT_TO_SYSCALL_NAMES: &[(&str, &[&str])] = &[
{chr(10).join(mapping_lines)}
];
"""
    args.output.write_text(generated)


if __name__ == "__main__":
    main()
