[package]
name = "rustagon-scap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
async-trait = "0.1"
aya = "0.13"
rustagon-common = { path = "../rustagon-common" }
tokio = { version = "1", features = ["macros", "net", "rt", "time"] }
